project:
  type: book
  output-dir: docs

book:
  title: "Open Education Book"
  repo-url: https://github.com/gerkovink/openeducationbook
  repo-branch: dev
  repo-actions: [edit, issue]
  author: 
  - name: Hanne Oberman
    orcid: 0000-0003-3276-2141
    email: h.i.oberman@uu.nl
    # affiliations: 
    # - name: 
  - name: Duco Veen
    orcid: 0000-0002-8352-7574
    email: d.veen@uu.nl
    # affiliations: 
    # - name: ""
  - name: Gerko Vink
    orcid: 0000-0001-9767-1924
    email: g.vink@uu.nl
    # affiliations: 
    # - name: ""
  date: last-modified
  chapters:
    - index.qmd
    - intro.qmd
    - open_education.qmd
    - where_to_start.qmd
    - creating_content.qmd
    - keeping_up_to_date.qmd
    - resources.qmd
    - impact.qmd
    - part: examples.qmd
      chapters:
      - example_lecture.qmd
      - example_course.qmd
  appendices:
    - references.qmd

bibliography: references.bib

format:
  html:
    toc-depth: 3
    include-after-body: custom.html
    theme: cosmo
  pdf:
    documentclass: scrreprt



