# Content {#sec-content}

In this Chapter we aim to provide some guidance on how to create content with openness in mind and updating content that you have made open. Clearly we cannot create content for you, but we hope that the suggestions in this Chapter will be useful considerations for when you design your materials or update them. What we also won't do here is help you to structure your curriculum. There are plenty of other resources for that, see for instance @mckeachie2013mckeachie or @marshall_handbook_2020 [Chapter 9] on developing an inclusive curriculum. What we focus on here is what we think is important in relation to thinking open whilst creating new content or updating what you have. Moreover, we started out with two separate tracks in this book, one for prospectively creating new materials and one for retrospectively opening up existing materials. In this Chapter these two tracks come together naturally. After this Chapter both tracks will be merged into one and continue together. 

## Creating new content

When you are creating new content, you have the opportunity to design it with openness in mind. This means that you can think about how you can make your content accessible to a wide range of learners, how you can make it easy to update, and how you can make it easy to reuse. You can plan thing such that your life will be easier in the future too. In this section we will provide some suggestions on how to do this.

### Open by Design

In @sec-open_education we described the core principles and pedagogical foundations of open education. We will not repeat them here, but we do want to highlight some of the key principles that we think are important to consider when creating content. When crafting OER with an open approach, it's crucial to embed the ethos of openness into every aspect of the creation process. This means not only making your content freely accessible but also ensuring it resonates with a broad and diverse audience and adheres to idea of transparency, inclusivity and accessibility. It is optimal to design content that accommodates a wide range of learners, including those with disabilities. Here are some suggestions you can keep in mind when designing content:

- **Universal Design for Learning (UDL)**: Adopt UDL principles to create materials that offer multiple means of engagement, representation, and expression. This approach ensures that learning experiences are accessible and meaningful for all students, regardless of their learning style or ability. For more information, see the UDL guidelines [here](https://udlguidelines.cast.org/) [@cast_universal_2018].
  
- **Cultural Sensitivity**: Be mindful of cultural diversity in your content. This includes using inclusive language, examples, and illustrations that reflect a variety of backgrounds and experiences. Avoid cultural biases and stereotypes to ensure your content is welcoming and relatable to a broad audience.

- **Technology and Formats**: Choose formats that are widely accessible. For instance, while videos can be engaging, they should be complemented with captions or transcripts for learners with hearing impairments. Similarly, text materials should be screen-reader friendly, and interactive tools should be navigable for users with different abilities. When designing figures, consider using color-blind friendly palettes and patterns.

These suggestions to content creation not only aligns with the philosophy of open education, they also enhances the overall quality and impact of the educational materials. Your work will be more accessible, more engaging, and more relevant to a broader audience.


### Prepare for the Future

Creating open educational resources (OER) is not just about addressing current educational needs; it's also about building resources that can evolve and remain relevant over time. As you develop your OER, it’s essential to consider how they will be maintained, updated, and used in the future. Here are some strategies to ensure your content remains valuable and adaptable for years to come:


**Designing for Adaptability**

- **Modular Design**: Create your content in modular segments that can be easily updated or reorganized. This approach allows for easier revisions and additions without needing to overhaul the entire resource. Most educational resources will naturally follow such a modular design. But make sure that, for instance, cross references are adaptive to changes in the content.
- **Software use**: Try to avoid proprietary software that may become inaccessible in the future. For instance, if you use a proprietary software to create your content, make sure that you can export your work to a standard format that can be used with other software. This is especially important for editable files like documents, images, and videos. Realize that future you might not have access to licences for the software you used to create your content. Additionally, consider any software that your students might need to use. Students might have access to software through their university. But once they graduate, they might not have access to the software anymore. In these cases, consider using Open Source Software. 


**Files and Formats**

- **Preserve Source Materials**: Always keep the raw, editable files of your content, not just the final published versions. For instance, maintain the original editable files for documents, images, and videos.
- **Version Control**: Use version control systems like [Git](https://git-scm.com/) and platforms like [GitHub](https://github.com/) or [GitLab](https://about.gitlab.com/) to track changes and manage updates to your content. This is especially useful for collaborative projects. See also @sec-resources. 
- **Format Considerations**: Choose file formats that are widely used and likely to be supported in the long term. For example, standard formats like HTML, PDF, and MP4 are more likely to be accessible and usable in the future compared to proprietary formats.

**Feedback and Update Mechanism**

- **Feedback Channels**: Establish clear channels for users to provide feedback on your resources. This can be through online forms, email, or within the learning platform itself. This feedback can be used to inform future updates and revisions.
- **Regular Review and Update Cycles**: Set a schedule for regularly reviewing and updating your content. This ensures that your materials stay up-to-date with the latest information and educational practices. Usually this is a natural cycle for educational resources. But it is important to be aware of this cycle and to plan time to update.

**Community Involvement**

- **Encourage Community Contributions**: Foster a community around your OER where educators, learners, and other stakeholders can contribute to the content’s development and refinement.
- **Collaboration Platforms**: Consider utilizing platforms that allow for collaborative contributions and discussions, such as wikis or community forums.
- **Open Licenses**: Use open licenses that allow others to use, adapt, and redistribute your content. This encourages community involvement and allows for the creation of derivative works. See also @sec-licensing.


By implementing these strategies, you do everything you can to ensure that your OER remain valuable, relevant, and accessible for years to come. Preparing for the future is about building flexibility into your resources and fostering a culture of continuous improvement and community engagement.


## Updating Content {#sec-updating_content}

In @sec-making_it_open we discussed opening up existing materials and the actions that need to be taken to make them open. In this section we discuss how to keep content up to date and how to update content after it has been made open. Our focus will be on getting more and more open, and not on the process of updating content itself. For instance, after we evaluated the content that we initially wanted to open up, we may have found some parts not to compatible with the licences we wanted the end product to have. Maybe at a revision period, those parts are updated with new content that can be incorporated in the OER. Even thought the principles of updating content also apply to cases where the content was designed to be open from the start, we focus on the case where content was not open from the start.


### Assessing and Prioritizing Updates

When updating content, it is important to assess and prioritize the updates that need to be made. This is especially important when updating content that has been made open. Depending on your situation, not all content might have been opened at once. Updates are an excellent opportunity to open up more content, renew content that had restrictive licences or change software that was not open source in your original content. The following steps can be taken to assess and prioritize updates:

1. **Regular Evaluation**: Establish a routine for periodically assessing your OER. Determine if the content still aligns with current academic standards, technological advancements, and user feedback. Check your mapping of the licences and spot opportunities to become even more open. Most likely your periodical update will align with the next iteration of your course. It can be convenient to keep a list of issues that need to be addressed as you find them. This way you can easily keep track of what needs to be updated and why and you don't forget anything.
2. **Prioritize Based on Impact**: Identify which parts of your OER would benefit most from updates. Prioritize sections that are either outdated or have the most significant impact on learning outcomes. After content considerations you can make a priority list based on where the most gain is to be made in terms of openness.
3. **Prioritize Based on Resources**: Consider the resources you have available to make updates. If you have limited resources, balance resources and impact to determine which updates are feasible. Maybe this means that the most impactful change doesn't happen in the first iteration, but in the second or third. 

**Technical Aspects of Updating**

When updating your OER, it's incredibly useful to incorporate effective version control systems. These systems not only allow for the efficient management of updates but also serve as a tool for documenting changes. By keeping a transparent record of each update, you ensure that users always have access to the latest versions of your materials. And, not unimportant, you always have a record of what changes you made and why. This approach not only enhances the user experience but shows the world that your materials get updated and are continuously improved. With each update we advise to also update your mapping of the licences involved in your OER. Also consider to create a Digital Object Identifiers (DOI) for your OER. This will make it easier to track the impact of your OER, see more in @sec-impact. In case you do, make sure to update the DOI and version of your OER when you update your OER.


## Testing {#sec-testing}

Being open is not just about making content available, it is also about making sure that the content is accessible and usable. Just putting content online is not enough. You want to know that people can actually use the content of your OER after putting in all that effort to create them or opening them up. Ensuring that your open educational resources function effectively across various platforms and technologies is what we can call the "Testing" phase. The testing is meant to assess the technical robustness and user accessibility of your content. This is were our two tracks start to merge together, all materials should be tested before you are ready to share your OER.

### Technical Compatibility

- **Cross-Device Accessibility**: Test whether your content can be accessed across different devices such as smartphones, tablets, laptops, and desktop computers.
- **Operating System Compatibility**: Ensure that the content functions well on various operating systems, including Windows, macOS, Linux, iOS, and Android.
- **Browser Compatibility**: Verify that your content displays correctly in various web browsers like Chrome, Firefox, Safari, and Edge.
- **Screen Size Adaptability**: Test how your content adapts to different screen sizes, ensuring readability and usability across devices.
- **Internet connection Speed**: Ensure that your content loads efficiently even on slower connections, which is crucial for users in regions with limited bandwidth. For instance, optimize image and video sizes without compromising quality. The [Google PageSpeed Insights](https://developers.google.com/speed/pagespeed/insights/) tool can be helpful in analyzing page load times and offering optimization suggestions.


### Load Testing

- **Handling High Traffic**: If your content is hosted online, conduct load testing to ensure that your server can handle high traffic without significant performance issues. Or in any case, figure out if you can handle the demand of the amount of students you have. We can assure you from personal experience that it is not fun to have servers crash because too many people are trying to access your content at the same time in your classroom. This can be a real shame of the time spent on developing the content.

### Iterative Approach

Treat testing as an ongoing process of continuous improvement. Use the feedback and data collected to make continuous improvements, enhancing the accessibility, usability, and overall quality of your content.

- **Feedback from Actual Users**: Collect feedback from a group of test users representing your target audience. Or collect feedback during actual usage. This can provide valuable insights into the usability, engagement level, and overall learner experience.
- **Ease of Navigation**: Assess how easy it is for users to find and navigate through the content. Ensure that navigation elements are intuitive and user-friendly.
- **Accessibility**: Ensure that your OER are fully accessible to learners with disabilities. This includes checking for screen reader compatibility, ensuring proper color contrast, and providing captions or transcripts for videos. Utilize a tool like [WAVE (Web Accessibility Evaluation Tool)](https://wave.webaim.org/) to evaluate your content for accessibility compliance. 

By rigorously testing your OER, you not only enhance its technical quality but also ensure a more pleasant and effective learning experience for all users.





## Keeping Track

To help you keep track of all the steps we discussed, we update our mapping in @fig-planning_for_openness3 and @fig-making_it_open3. Here you can find back the steps that have been described up to this point. Moreover, in @fig-making_it_open_all0 you will see how the two tracks merge together.

```{mermaid}
%%| fig-cap: Mapping the actions that need to be taken to create OER prospectively. Here the actions for the content stage are added to this map. 
%%| label: fig-planning_for_openness3

timeline
  title Starting Open Prospectively
  section Planning for Openness
    Scoping : Setting clear goals
           : Understanding your audience
           : Stakeholder management
           : Evaluation of success
    Practicalities : Resources and time commitment
                   : Licensing
                   : Platform and content
  section Content
    Creating content: Open by Design
                    : Testing
                    : Prepare for the Future
  section Launch and Implementation
    ... : ...
  section Leveraging Benefits
    ... : ...

                      
```



```{mermaid}
%%| fig-cap: Mapping the actions that need to be taken to make resources open retrospectively. Here the actions for the evaluating existing resources stage are added to this map.
%%| label: fig-making_it_open3

timeline
  title Opening Up Existing Educational Materials
  section Planning for Openness
    Evaluating Existing Resources : Licencing
                            : Stakeholder Management
  section Content
    ... : ...
  section Launch and Implementation
    ... : ...
  section Leveraging Benefits
    ... : ...
   

```


```{mermaid}
%%| fig-cap: Mapping the actions that need to be taken to create OER. A map for the actions that need to be taken when working prospectively or retrospectively and where they start to converge. 
%%| label: fig-making_it_open_all0

graph TD
    A[Starting Open Prospectively] 
    B[Opening Up Existing Educational Materials]
    
    subgraph S1["Planning for Openness"]
    A1a[Scoping]
    A1b[Practicalities]
    end
   
    subgraph S2[New Content]
    A2a[Creating content]
    end

    subgraph S3["Planning for Openness"]
    B1a[Evaluating Existing Resources]
    end

    subgraph S4[Updating Content]
    B2a[Assessing and Prioritizing Updates]
    end   
    
    A --> S1 --> S2 --> S4
    B --> S3 --> S4

    subgraph S5["Launch and Implementation"]
    C1a[...]
    end   
  
    subgraph S6["Leveraging Benefits"]
    D1a[...]
    end   
  
    S4 --> S5
    S5 --> S6
    
    style S1 fill:#8686FF,color:#FFFFFF,stroke-width:2px
    style S3 fill:#8686FF,color:#FFFFFF,stroke-width:2px
    style A1a fill:#A1A1FF,color:#FFFFFF,stroke-width:2px
    style A1b fill:#A1A1FF,color:#FFFFFF,stroke-width:2px
    style B1a fill:#A1A1FF,color:#FFFFFF,stroke-width:2px
    style S2 fill:#FFFF78,color:#000000,stroke-width:2px
    style S4 fill:#FFFF78,color:#000000,stroke-width:2px
    style A2a fill:#FFFF90,color:#000000,stroke-width:2px
    style B2a fill:#FFFF90,color:#000000,stroke-width:2px
    style S5 fill:#D7FF86,color:#000000,stroke-width:2px
    style C1a fill:#FFFFA1,color:#000000,stroke-width:2px
    style S6 fill:#C386FF,color:#FFFFFF,stroke-width:2px
    style D1a fill:#EAA1FF,color:#FFFFFF,stroke-width:2px
```
