# Generating Impact {#sec-impact}

Welcome to the crucial final phase in your journey with OER `Leveraging Benefits` and Generating Impact. This chapter is dedicated to sharing some examples of how you can maximize the impact of your OER. We will explore a few key resources and strategies that can significantly amplify the impact of your OER and help you get credit for your work. 

## Zenodo

[Zenodo](https://zenodo.org) is a general-purpose open repository developed under the European [OpenAIRE](https://www.openaire.eu) program and operated by [CERN](https://home.cern). It was launched in May 2013 as a means for researchers in various fields to comply with open science deposit requirements, especially in the absence of an institutional repository. Zenodo allows researchers to deposit a wide array of research-related digital artifacts, including research papers, data sets, research software, and reports. Each submission is assigned a persistent digital object identifier (DOI), facilitating easy citation of the stored items. This way you can get credit for your work on the OER.

Zenodo [reported significant milestones](https://blog.zenodo.org/2021/12/07/2021-12-07-hardening-our-service/), such as hosting over 1 petabyte of data and receiving 15 million yearly visits. 

Zenodo's approach to Open Science is inclusive and barrier-free, with no requirements on format, size, access restrictions, or license for submissions. This makes it an effective platform for sharing, curating, and publishing data and software for researchers worldwide. Furthermore, Zenodo's simple web interface is complemented by a rich API, allowing for third-party tools and services to integrate with it as part of their workflow. One of its key features is its integration with GitHub repositories.

For Open Science, Zenodo helps researchers receive credit by making results citable and integrates them into existing reporting lines to funding agencies like the European Commission. Zenodo's metadata is openly available under a [CC0](https://creativecommons.org/public-domain/cc0/) license, and its open content is accessible through open APIs. The repository is a concrete alternative to commercial services, aiming to serve as a viable solution for current and future generations in the scholarly communication landscape.

### Starting a Zenodo repository

Zenodo enables to share and preserve your digital research objects (publications, data, software, presentations, etc.) in three simple steps:

1. **Upload:** Upload the files you want to share.
2. **Describe:** Describe the files with minimal metadata such as title and creators.
3. **Publish:** When ready, hit the publish button to share your research.

Once you publish, Zenodo will automatically assign a Digital Object Identifier (DOI) to your record. Your research output will be findable and citable immediately. Zenodo provides a straightforward and user-friendly outline of this procedure [in its documentation](https://help.zenodo.org/docs/get-started/quickstart/).

### Zenodo and GitHub
Referencing and citing content for scientific purposes on GitHub is not straightforward. GitHub is a code repository, not a publishing platform. GitHub does not provide a DOI for repositories, and the only way to cite a GitHub repository is to use the URL. However, the URL is not persistent, and the content of the repository can change over time. Zenodo provides a solution to this problem by integrating with GitHub. Zenodo can create a snapshot of a GitHub repository and assign a DOI to it. This DOI can then be used to cite the repository. This process is clearly outlined in the [Zenodo documentation](https://guides.github.com/activities/citable-code/) and [GitHub documentation](https://docs.github.com/en/repositories/archiving-a-github-repository/referencing-and-citing-content)

## Edusources

[Edusources](https://edusources.nl) is a comprehensive digital platform in the Netherlands, designed to enhance the accessibility and sharing of Open Educational Resources for the Dutch education sector. This platform is pivotal in the distribution and utilization of digital learning resources, catering to a broad spectrum of needs across various educational levels. Edusources is not designed to host files but rather to provide a centralized location for educators to discover and disseminate digital learning materials. The hosting part can be done by other platforms, such as Zenodo, OSF, GitHub or Surfsharekit (see @sec-resources).

One of the key features of Edusources is its extensive repository of digital learning materials. The platform offers more than 10,000 learning resources contributed by subject teachers and educational communities. These resources encompass a diverse range of materials including knowledge clips, PowerPoint presentations, PDFs, online modules, and practice tests. The platform's design not only facilitates the discovery of these resources but also encourages educators to contribute their own materials, thereby continually enhancing the quality and variety of the collection.

## Keeping Track

Here we are! The final update of our maps. In this Chapter we discussed ways to take credit and disseminate your OER. We update our mapping in @fig-planning_for_openness5 and @fig-making_it_open5. Here you can find back the steps that have been described up to this point. Moreover, in @fig-making_it_open_all2 the two paths are shown together. 

```{mermaid}
%%| fig-cap: Mapping the actions that need to be taken to create OER prospectively. Here the actions for the Leveraging benefits stage are added to this map.
%%| label: fig-planning_for_openness5

timeline
  title Starting Open Prospectively
  section Planning for Openness
    Scoping : Setting clear goals
           : Understanding your audience
           : Stakeholder management
           : Evaluation of success
    Practicalities : Resources and time commitment
                   : Licensing
                   : Platform and content
  section Content
    Creating content: Open by Design
                    : Prepare for the Future
                    : Testing
  section Launch and Implementation
    Host your OER : Pick a Platform
  section Leveraging Benefits
    Share your OER : Make it Discoverable
                   : Make it Citable

                      
```



```{mermaid}
%%| fig-cap: Mapping the actions that need to be taken to make resources open retrospectively. Here the actions for the Leveraging benefits stage are added to this map.
%%| label: fig-making_it_open5

timeline
  title Opening Up Existing Educational Materials
  section Planning for Openness
    Evaluating Existing Resources : Licencing
                            : Stakeholder Management
  section Content
    Updating Content : Assessing and Prioritizing Updates
                     : Testing
  section Launch and Implementation
    Host your OER : Pick a Platform
  section Leveraging Benefits
    Share your OER : Make it Discoverable
                   : Make it Citable
   

```


```{mermaid}
%%| fig-cap: Mapping the actions that need to be taken to create OER. A map for the actions that need to be taken when working prospectively or retrospectively and where they start to converge. 
%%| label: fig-making_it_open_all2

graph TD
    A[Starting Open Prospectively] 
    B[Opening Up Existing Educational Materials]
    
    subgraph S1["Planning for Openness"]
    A1a[Scoping]
    A1b[Practicalities]
    end
   
    subgraph S2[New Content]
    A2a[Creating content]
    end

    subgraph S3["Planning for Openness"]
    B1a[Evaluating Existing Resources]
    end

    subgraph S4[Updating Content]
    B2a[Assessing and Prioritizing Updates]
    end   
    
    A --> S1 --> S2 --> S4
    B --> S3 --> S4

    subgraph S5["Launch and Implementation"]
    C1a[Host your OER]
    end   
  
    subgraph S6["Leveraging Benefits"]
    D1a[Share your OER]
    end   
  
    S4 --> S5
    S5 --> S6
    
    style S1 fill:#8686FF,color:#FFFFFF,stroke-width:2px
    style S3 fill:#8686FF,color:#FFFFFF,stroke-width:2px
    style A1a fill:#A1A1FF,color:#FFFFFF,stroke-width:2px
    style A1b fill:#A1A1FF,color:#FFFFFF,stroke-width:2px
    style B1a fill:#A1A1FF,color:#FFFFFF,stroke-width:2px
    style S2 fill:#FFFF78,color:#000000,stroke-width:2px
    style S4 fill:#FFFF78,color:#000000,stroke-width:2px
    style A2a fill:#FFFF90,color:#000000,stroke-width:2px
    style B2a fill:#FFFF90,color:#000000,stroke-width:2px
    style S5 fill:#D7FF86,color:#000000,stroke-width:2px
    style C1a fill:#FFFFA1,color:#000000,stroke-width:2px
    style S6 fill:#C386FF,color:#FFFFFF,stroke-width:2px
    style D1a fill:#EAA1FF,color:#FFFFFF,stroke-width:2px
```