# Introduction

In this book we take you with us on a journey to the world of Open Educational Resources (OER). We will discuss what OER are, how you can create them and how you can spread and share them. We will also discuss some of the benefits and challenges of OER. We will try to be brief where we can in this book. It is not an exhaustive guide to OER, but rather a starting point for you to explore the world of OER. We do invite your to contribute to the book. At the end of this introduction in @sec-contributors contributions will be acknowledged.

Because we are aware that, like in many other books and readings, you will encounter a lot of abbreviations, we have decided to included a list of the most important ones right at the start. Here is a list of the abbreviations that you will encouter in this book. 

Abbreviation | Meaning
-----|-----
OER | Open Educational Resources
MIT OCW | MIT OpenCourseWare
IP | Intellectual Property
GNU GPL | GNU General Public License
CC | Creative Commons
CC-BY | Creative Commons Attribution
CC-BY-SA | Creative Commons Attribution-ShareAlike
CC-BY-NC-SA | Creative Commons Attribution-NonCommercial-ShareAlike
GNU-GFDL | GNU Free Documentation License
DOI | Digital Object Identifier

: Abbreviations used in the book and their meanings.


We hope that you will find this book useful to start creating and sharing your own OER. If you have any questions, comments or suggestions, please do not hesitate to contact us.


## Contributors {#sec-contributors}

Before we continue to the content of the book. Here is a list of contributors that helped to make this book possible.

```{python}
#| echo: false
import requests, json

logins = json.loads(requests.get("https://api.github.com/repos/gerkovink/openeducationbook/contributors?per_page=100").text)
for login in logins:
    print(f"{login['login']} has {login['contributions']} commits")
```