# Resources  {#sec-resources}

This chapter on resources serves as a guide to the various tools and platforms that can be used to create, manage, and disseminate open educational resources (OER). The overview is not comprehensive but rather provides a starting point for educators and institutions looking to incorporate open education into their teaching and learning practices. The chapter will help you with the `Launch and Implementation` stage of creating your OER, see @sec-where_to_start.

The initial authors have mostly made descriptions of tools they use themselves. We welcome anyone to contribute descriptions of additional resources so that we can become more complete. Just create a pull request to add content to the book. In the online version of the book there should be a `Edit this page` button beneath the Table of contents. You will be recognized as a contributor to the book in the [contributors list](#sec-contributors). 

<!-- If you are not familiar with GitHub, please see the screen capture below on how to add content to the book. -->
<!-- <FONT COLOR="#ff0000"> -->
<!-- **Add screencapture on how to edit the book.** -->
<!-- </FONT> -->

## Github 
[GitHub](https://github.com) is a powerful and versatile platform, transcending its traditional role as a hub for software development. At its core, GitHub is a web-based interface that utilizes [`Git`](https://git-scm.com), a version control system allowing multiple people to work together on projects. This functionality of GitHub is not limited to code; it extends seamlessly into the development and management of open educational resources.

The true strength of GitHub lies in its collaborative nature. Developers, educators and students can jointly create, modify, and enhance software code, course materials, textbooks, and other educational and non-educational resources. This process is facilitated by GitHub's intuitive features like 'forking', where users can make their own copy of a project to modify, and 'pull requests', which allow them to suggest changes to the original project. These features encourage a community-driven approach to development and education, where knowledge is not just consumed but actively constructed and refined by its users.

GitHub's version control capabilities are equally useful in an educational context. Educators can track and manage changes to materials over time, ensuring that resources are continually updated and improved. This aspect fosters a dynamic educational environment where content evolves in response to new information, pedagogical strategies, and user feedback.

Moreover, GitHub hosts a plethora of diverse educational content, offering an expansive resource pool for educators and students. The platform's open nature aligns perfectly with the ethos of open science and open education, providing unrestricted access to a wide array of learning materials. Whether it’s programming tutorials, scientific research, or entire course curricula, GitHub serves as a one-stop shop for educational resources.

A notable initiative by GitHub in the education sector is [GitHub Education](https://education.github.com/). This program provides students and educators with free access to the best developer tools in one place, along with opportunities to learn and collaborate. It's a valuable resource for those looking to integrate technology and collaboration in their teaching and learning processes. GitHub Education offers various benefits like free access to GitHub Enterprise or Team plans, automation tools, continuous integration, cloud hosting services, and more, all of which are pivotal in creating an interactive and engaging learning environment.

By leveraging GitHub in the educational context, educators and institutions can break away from traditional, siloed approaches to teaching. The platform encourages an open, collaborative, and constantly evolving educational landscape, aligning with the modern pedagogical focus on accessibility, flexibility, and learner-centered approaches. In an era where digital literacy and collaborative skills are paramount, GitHub stands as an exemplary tool in the arsenal of open education.

::: callout-tip
# GitHub Pages
This service allows users to create and host a website directly from their GitHub repository. It is an invaluable tool for educators and institutions aiming to disseminate their open educational resources (OER) to a wider audience in a more structured and accessible manner.

GitHub Pages operates by transforming plain text or markdown files in a GitHub repository into a fully-fledged website. This capability is especially beneficial for educators looking to share course materials, lecture notes, or even entire textbooks in an easily navigable format. The simplicity of setting up a GitHub Pages site means that educators, regardless of their technical expertise, can establish an online presence for their course materials without the need for complex web development skills.

One of the primary advantages of using GitHub Pages for hosting educational content is its seamless integration with the rest of the GitHub ecosystem. Updates to course materials in the GitHub repository are automatically reflected on the associated GitHub Pages site. This ensures that students always have access to the most current version of the resources, fostering a dynamic and up-to-date learning environment.

Moreover, GitHub Pages supports custom domain names and offers a range of themes and layouts, allowing educators to personalize their site to align with their course's branding or their institution's visual identity. This feature enhances the user experience for students and other stakeholders who visit these educational websites. 

Examples of informative academic course pages hosted on GitHub include:

- [STA 210: Regression Analysis at Duke University](https://sta210-s22.github.io/website/) 
- [INFOMDWR Data Wrangling and Data Analysis at Utrecht University](https://infomdwr.nl) 
- [Markup Languages and Reproducible Programming in Statistics at Utrecht University](https://www.gerkovink.com/markup/course-overview.html)
- [A gentle introduction to Bayesian Estimation](https://utrechtuniversity.github.io/BayesianEstimation/)

For a quickstart with open educational materials on GitHub, you can use a [template repository](https://github.com/hanneoberman/open_education_template). Such a template sets up a folder structure for hosting educational contents with GitHub Pages. Then, you only have to fill in the course contents, and your course website will be live right away.
:::

### How to host your own website on GitHub Pages
Github has [build a great website](https://pages.github.com) to get you started with hosting your own GitHub page. Many GitHub course repositories are templates and can be easily copied and modified to your liking. More information about template repositories can be found [here](https://docs.github.com/en/issues/planning-and-tracking-with-projects/managing-your-project/managing-project-templates-in-your-organization)

## Open Science Framework
[The Open Science Framework (OSF)](https://osf.io) stands as a stable ally in the quest for open science, extending beyond its original design as a tool for research project management. Its adaptability and comprehensive features make it an excellent choice for educators seeking to organize and disseminate course materials, assignments, and collaborative research projects. OSF's flexibility and ease of use cater to a wide range of educational needs, making it a valuable asset in the open education landscape.

One of the most compelling aspects of OSF is its ability to integrate seamlessly with other platforms like GitHub, Google Drive, and Dropbox. This integration transforms OSF into a central hub for open educational projects, streamlining the management of diverse resources. Educators can leverage this integration to maintain a cohesive and organized repository of course materials, facilitating easy access and consistent updates. By connecting various tools under one roof, OSF ensures that the management of educational materials is both efficient and effective.

OSF's commitment to open access is particularly noteworthy. By promoting the free availability of educational research, OSF becomes a treasure trove for educators aiming to infuse their teaching with cutting-edge knowledge and methodologies. This open access principle aligns perfectly with the ethos of open education, where barriers to knowledge are dismantled, and learning is made universally accessible. Educators and students alike can benefit from the wealth of research available on OSF, enriching their educational experience and fostering a culture of continuous learning.

Furthermore, OSF's capacity to facilitate collaboration across institutions is a game-changer in the realm of open education. It enables educators and students from different institutions to engage in joint projects, share resources, and exchange ideas, thereby creating a vibrant, interconnected community of learners and teachers. This collaborative environment not only enhances the quality of educational materials but also fosters a sense of global citizenship and shared purpose among participants.

In essence, OSF embodies the spirit of open education. It provides a structured, integrated, and collaborative platform for educators and students to access, create, and share knowledge. By leveraging OSF's capabilities, the open education movement can continue to grow and evolve, breaking down traditional barriers to education and paving the way for a more inclusive, dynamic, and interconnected learning experience. The use of OSF in open educational practices exemplifies the transformative power of technology in education, offering new pathways for teaching, learning, and research in the digital age.

## SURFsharekit
[SURFsharekit](https://surfsharekit.nl/) is a Dutch online repository service in the tailored for higher education. It serves as a digital storage platform where graduation theses, research publications, and learning materials can be sustainably stored and shared. This service is particularly notable for its emphasis on open access, ensuring that the materials stored are as accessible as possible. It encourages knowledge sharing among various educational institutions and adheres to international standards for information exchange.

The repository is harvested by portals like [HBO Kennisbank](https://hbo-kennisbank.nl/index) and [Edusources](https://edusources.nl) (see @sec-impact), enhancing the visibility and reach of the stored materials. SURFsharekit represents a significant tool for higher education institutions in the Netherlands, promoting open access and facilitating easy sharing of knowledge and resources across various platforms.


## Keeping Track

In this chapter on `Launch and Implementation` we have given examples of where you can host your OER. To help you keep track of all the steps we discussed, we update our mapping in @fig-planning_for_openness4 and @fig-making_it_open4 as we have done everytime before. Note that from here on out the two paths have merged together. You can see this in @fig-making_it_open_all1. 

```{mermaid}
%%| fig-cap: Mapping the actions that need to be taken to create OER prospectively. Here the actions for the Launch and Implementation stage are added to this map. 
%%| label: fig-planning_for_openness4

timeline
  title Starting Open Prospectively
  section Planning for Openness
    Scoping : Setting clear goals
           : Understanding your audience
           : Stakeholder management
           : Evaluation of success
    Practicalities : Resources and time commitment
                   : Licensing
                   : Platform and content
  section Content
    Creating content: Open by Design
                    : Prepare for the Future
                    : Testing
  section Launch and Implementation
    Host your OER : Pick a Platform
  section Leveraging Benefits
    ... : ...

                      
```



```{mermaid}
%%| fig-cap: Mapping the actions that need to be taken to make resources open retrospectively. Here the actions for the Launch and Implementation stage are added to this map.
%%| label: fig-making_it_open4

timeline
  title Opening Up Existing Educational Materials
  section Planning for Openness
    Evaluating Existing Resources : Licencing
                            : Stakeholder Management
  section Content
    Updating Content : Assessing and Prioritizing Updates
                     : Testing
  section Launch and Implementation
    Host your OER : Pick a Platform
  section Leveraging Benefits
    ... : ...
   

```


```{mermaid}
%%| fig-cap: Mapping the actions that need to be taken to create OER. A map for the actions that need to be taken when working prospectively or retrospectively and where they start to converge. 
%%| label: fig-making_it_open_all1

graph TD
    A[Starting Open Prospectively] 
    B[Opening Up Existing Educational Materials]
    
    subgraph S1["Planning for Openness"]
    A1a[Scoping]
    A1b[Practicalities]
    end
   
    subgraph S2[New Content]
    A2a[Creating content]
    end

    subgraph S3["Planning for Openness"]
    B1a[Evaluating Existing Resources]
    end

    subgraph S4[Updating Content]
    B2a[Assessing and Prioritizing Updates]
    end   
    
    A --> S1 --> S2 --> S4
    B --> S3 --> S4

    subgraph S5["Launch and Implementation"]
    C1a[Host your OER]
    end   
  
    subgraph S6["Leveraging Benefits"]
    D1a[...]
    end   
  
    S4 --> S5
    S5 --> S6
    
    style S1 fill:#8686FF,color:#FFFFFF,stroke-width:2px
    style S3 fill:#8686FF,color:#FFFFFF,stroke-width:2px
    style A1a fill:#A1A1FF,color:#FFFFFF,stroke-width:2px
    style A1b fill:#A1A1FF,color:#FFFFFF,stroke-width:2px
    style B1a fill:#A1A1FF,color:#FFFFFF,stroke-width:2px
    style S2 fill:#FFFF78,color:#000000,stroke-width:2px
    style S4 fill:#FFFF78,color:#000000,stroke-width:2px
    style A2a fill:#FFFF90,color:#000000,stroke-width:2px
    style B2a fill:#FFFF90,color:#000000,stroke-width:2px
    style S5 fill:#D7FF86,color:#000000,stroke-width:2px
    style C1a fill:#FFFFA1,color:#000000,stroke-width:2px
    style S6 fill:#C386FF,color:#FFFFFF,stroke-width:2px
    style D1a fill:#EAA1FF,color:#FFFFFF,stroke-width:2px
```