# Where do you start?

Congratulations on making it this far! Your interest in open educational materials, and your willingness to learn about and implement them, is a testament to your dedication to accessible, equitable, and collaborative learning. Thank you for your commitment to this approach in education.

This chapter is an important waypoint in your open education journey. You've learned about what open education entails in @sec-open_education, and now, you might be wondering how to practically apply it in your own context. We've designed this chapter to guide you through the first steps in that process.

We begin by discussing the choice between making educational materials open prospectively or retrospectively. Both these approaches offer unique challenges and opportunities. Although prospective design of open educational materials will be easier in practice. Understanding the differences and challenges can help you make informed decisions when designing or adapting your resources. In this chapter we will take the first steps in the process of starting to create new open educational materials or adapting existing materials to make them open. We start building practical checklists to help you navigate this process.

Finally, we delve into the legalities associated with open education, focusing on licensing. This can often seem daunting, but it's a crucial aspect to consider. We'll dissect complex terms like Intellectual Property, Copyright, and Public Domain, making them more approachable. We'll also look at the role of Creative Commons licenses, particularly cc-by and cc-by-sa, in facilitating the sharing and usage of open educational materials.

## Making it open: Prospective or Retrospective

Embracing open education represents a profound shift in the way we create, share, and interact with educational resources. As you embark on this journey, one of the first decisions you'll encounter is whether to make existing educational materials open (retrospective), start new projects with open education in mind (prospective), or a combination of both. 

Each approach comes with its own set of challenges and rewards. On one hand, opening up existing materials can provide immediate benefits in terms of accessibility and collaboration. On the other hand, this approach can be time-consuming and complex, especially when dealing with issues such as copyright and the technical aspects of transforming existing resources into open formats. 

Starting fresh with open education in mind when developing new materials, however, can often be a more streamlined process. From the outset, you can design your resources to be open, eliminating the need for later adaptations. Yet, this approach may mean that valuable existing resources remain closed off, at least in the short term.

The decision between these two approaches is not a binary one. A successful open education initiative often incorporates elements of both strategies. Opening up materials is always a win, but it's crucial to strike a balance between feasibility, effort, and the eventual result. You might find that while some existing resources lend themselves well to being opened retrospectively, for others, it might be more worthwhile to leave them as they are and focus on incorporating open principles in new projects.

Remember, the ultimate goal is to improve the accessibility and adaptability of educational resources. Whether you achieve this by opening existing materials or designing new ones with openness in mind will depend on your unique circumstances, resources, and goals. Let's explore these two approaches in greater detail. 

## Starting Open Prospectively

Embarking on the journey of creating open educational materials is a rewarding endeavor, but like all significant initiatives, it requires structured planning and execution. This process is delineated into four pivotal stages:

1. **Planning for Openness**: This initial stage lays the foundation. It involves understanding the why, what, and for whom you are creating the materials. It's about aligning your objectives with the needs of your audience and considering the practicalities involved. Information on this stage will be presented in this chapter. 

2. **Creating Content**: Once the groundwork is established, the focus shifts to the content. This stage is dedicated to crafting high-quality, accessible, and engaging materials. It encompasses not just the creation, but also the considerations of format, adaptability, and inclusivity. In @sec-creating_content more details on this stage can be found. 

3. **Launch and Implementation**: Here, the prepared materials are introduced to the world. This phase involves selecting the right platform, ensuring easy access for your target audience, and setting up mechanisms for feedback and interaction. For this, you need to work with the right resources, details on which can be found in @sec-resources. 

4. **Leveraging Benefits**: The final stage revolves around the post-launch period. It's about amplifying the advantages of open materials, such as promoting educational equity, sharing your work with a broader audience, and fostering community collaboration. Moreover, it emphasizes the importance of continuous improvement based on feedback and evolving educational trends. See @sec-impact for more information. 

For each of these stages, we will delve into specific phases, breaking them down to offer a comprehensive understanding. For every phase, actionable steps will be outlined to guide you seamlessly through the process of starting open prospectively.

Prepare to embark on a fulfilling journey that not only enhances educational access but also fosters a culture of collaboration and continuous learning.

<!-- 1. Planning for Openness from the Start -->

<!-- - The importance of setting clear goals and understanding your audience. -->

### Planning for Openness: Scoping

When starting to think about creating open educational materials, scoping is a first foundational step. This section will guide you in defining your objectives and gaining insights into your learners' needs, ensuring that your open educational materials will be both purposeful and effectively tailored.

**Setting clear goals** and having a clear sense of direction is crucial when embarking on a journey to create open educational materials. What do you hope to achieve by making your educational materials open? Is it to increase (free) access to quality education, promote collaboration among learners, or adapt to diverse learning needs and styles? Having a clear understanding of your goals will guide your decisions throughout the project and help you measure your success. 

**Understanding your audience** will heavily influence the design and presentation of your open educational materials. Who are your learners? What are their learning needs and preferences? How tech-savvy are they? What languages do they speak? Do they have specific accessibility needs? An understanding of your audience will ensure that your open educational materials are relevant, useful, and accessible to those who need them.

Setting clear goals and understanding your audience might require some research and reflection, but it's worth the effort. These two aspects form the foundation upon which successful open education projects are built. In this section we help you to clarify your goals by means of asking you scoping questions. They ensure that your project stays focused, meets learners' needs, and achieves its intended impact. So before you delve into the details of creating open educational materials, take some time to outline your goals and understand your audience, [Exercise @exm-scoping_questions1] can help you. It's your first step towards a successful open education project.


<!-- :::: {.callout-note} -->
<!-- ::: {#exm-1 .custombox} [Exercise @exm-1]--> 
<!-- options to customize boxes with numbering -->
<!-- https://stackoverflow.com/questions/73288564/is-it-possible-in-quarto-to-create-custom-cross-references-to-callout-blocks -->

:::: {.callout-note icon=false appearance=simple}
::: {#exm-scoping_questions1 .custom}
# Scoping questions for goals and target audience

| Questions to Consider | Your Answers |
| --- | --- |
| What do you hope to achieve by making your educational materials open? |  |
| Who are your learners? |  |
| What are their learning needs and preferences? |  |
| How tech-savvy are your learners? |  |
| What languages do your learners speak? |  |
| Do your learners have specific accessibility needs? |  |
| Are there assignments? | |
| Do learners need to hand-in work? Or can it done online? | |

:::
::::

Now that you thought about your goals and target audience, the next step is choosing the right format and platform that suits your needs. In the realm of open education, choosing the appropriate format and platform for your materials is a decision of paramount importance. This choice influences how accessible, adaptable, and collaborative your resources will be.

**Format selection** pertains to the type of file or medium you'll use to present your content. For instance, while a PDF might be universally readable, it's not as editable as a Markdown or an Office document. Likewise, video materials may be engaging, but they might pose accessibility challenges without accompanying transcripts. [Exercise @exm-scoping_questions2] is meant to help you think though your choices. You can fill it out for each of your educational materials and start considering if you are using the right formats. 

:::: {.callout-note icon=false appearance=simple}
::: {#exm-scoping_questions2 .custom}
# Considerations for Choosing Format and Platform

| Questions to Consider                                      | Your Answers |
| --- | --- |
| Which educational format will you be using? (e.g., videos, text, interactive exercises) |  |
| How frequently do you anticipate updates to the material?  |  |
| Will there be collaboration with others in content creation or revision? |  |
| Is feedback from users/learners desirable?                 |  |
| Are there any other specific technical requirements or considerations for your materials? |  |
| Do the materials need to be editable?  |  |
| What file formats will you be sharing information in? (e.g., PDF, Powerpoint, Markdown, Jupyter Notebook) Are these formats able to handle the your goals above? |  |


:::
::::


**Platform selection**, on the other hand, is about where and how you host and share your content. The platform dictates how learners access your materials, how they interact with them, and how they collaborate or contribute. While we'll dive deeper into concrete options for platforms in @sec-resources, it's essential to reflect on a few questions when starting to think about designing open materials. A well-chosen format and platform can enhance the openness, reach, and impact of your educational materials, ensuring they resonate with and benefit your intended audience. But how far can, and do you want, to go. For now, we will leave you with a few questions to consider in [Exercise @exm-scoping_questions3].


:::: {.callout-note icon=false appearance=simple}
::: {#exm-scoping_questions3 .custom}
# Platform Choice Considerations

| Questions to Consider                                                      | Your Answers |
| --- | --- |
| Are you allowed to use any platform you choose for your course?            |  |
| How interactive do you want the learning experience to be?                 |  |
| Do you want interactions with students to be open and visible to the whole world? |  |
| Do you want assignments and student submissions to be public?              |  |
| What tech tools are your target audience familiar with?                    |  |
| Is community collaboration in content creation a goal?                     |  |
| Do you want insight into the collaboration between students?               |  |
| What kind of analytics or feedback mechanisms are you seeking?             |  |
| Would you like to see contributions in group assignments?                  |  |

:::
::::

**Stakeholder management** play a pivotal role in the success of any open education initiative. Their buy-in, or the extent to which they support and are committed to the project, can significantly influence its implementation and sustainability. When considering an open education initiative, it's essential to ensure that all key stakeholders, whether they be faculty, administration, and potentially students, are not only informed but also involved in the design process. Their unique perspectives, concerns, and insights can provide valuable feedback that can shape the direction and quality of the project. Additionally, their support can help to ensure longevity and sustainability of the project. 

However, along with the advantages of involving stakeholders comes the task of anticipating and navigating potential challenges and barriers. Resistance might arise from educators who are unfamiliar with or skeptical about the benefits of open education. Some learners might prefer traditional learning materials or have concerns about teaching in the open. By creating open educational materials, you put yourself out there and become vulnerable to criticism. You might receive feedback about the quality and relevance of your materials. Try to convince yourself and others that this is desirable, because in the long-run it will improve the quality of your materials. To help you with stakeholder management, you can use [Exercise @exm-stakeholder_questions] to consider each group of stakeholders and strategize on how best to involve them in your open education journey. Additionally, @sec-benefits and @sec-perception-of-threat provide some overviews of (perceived) augments for and against open education to help you in discussing open education with stakeholders.


:::: {.callout-note icon=false appearance=simple}
::: {#exm-stakeholder_questions .custom}
# Stakeholder Engagement and Concerns Evaluation

| Questions for Stakeholder Consideration                             | Your Answers       |
|---------------------------------------------------------------------|--------------------|
| Who are the relevant stakeholders for your open education initiative? |                    |
| Which stakeholders might view the initiative positively? Why?        |                    |
| Which stakeholders might view the initiative negatively? Why?        |                    |
| What specific concerns can you address or alleviate?                 |                    |
| What concerns might remain even after addressing them?               |                    |
| How do you plan to address or mitigate these remaining concerns?     |                    |

:::
::::


**Evaluation of success** is important to consider. Before we turn to the practicalities in our planning stage, we should determine when we would consider the first version of our open educational initiative a success. Success can be measured in various ways, and it's crucial to have clear metrics in place from the outset. Quantitative metrics, such as the number of users or downloads, can provide tangible evidence of the reach and uptake of your materials. For example, achieving a certain number of users within the first month of launch might be a benchmark for success, but perhaps not relevant if you develop the materials for a course with a fixed number of students. Qualitative measures can shed light on the actual impact and effectiveness of your materials. Feedback from users, testimonials, and direct observations can offer insights into how well the materials are meeting the needs of the learners. Did they find the resources engaging? Were the materials able to cater to diverse learning needs? These qualitative insights can guide future iterations, ensuring that the open educational materials continue to evolve and improve based on real-world feedback. Be gentle for yourself and don't expect to get everything right in the first iteration. But do consider what if important to you and your stakeholders and how you can measure that. [Exercise @exm-evaluation_question] can help you to ask what you consider important, [Example @exm-evaluation_question2] provides examples of how you can measure or investigate success.

Does it all feel like a bit much to keep track of? Don't worry, in @fig-planning_for_openness0 you can find back the steps that have been described. Additionally, the figure will be updated after each relevant section such that, step by step, the sequence of actions to create open educational materials will be mapped. 



```{mermaid}
%%| fig-cap: Mapping the actions that need to be taken to create open educational materials prospectively. Here the actions for the scoping phase in the planning stage are added to this map. 
%%| label: fig-planning_for_openness0

timeline
  title Starting Open Prospectively
  section Planning for Openness
    Scoping : Setting clear goals
           : Understanding your audience
           : Format Selection
           : Platform selection
           : Stakeholder management
           : Evaluation of success
    ... : ...
  section Creating content
    ... : ...
    ... : ...
  section Launch and Implementation
    ... : ...
    ... : ...
  section Leveraging Benefits
    ... : ...
    ... : ...

                      
```


:::: {.callout-note icon=false appearance=simple}
::: {#exm-evaluation_question .custom}
# Try to answer what is important to you

| Evaluation Criteria                               | Your Definition of Success                           |
|--------------------------------------------------|-----------------------------------------------------|
| I consider the implementation of the open educational materials a success when ... |    ...                                                 |
| I consider the implementation of the open educational materials a success when ... |    ...                                                 |

:::
::::


:::: {.callout-note icon=false appearance=simple}
::: {#exm-evaluation_question2}
# How you could define your success

| Key Performance Indicator (KPI)                   | How to Measure the KPI                                              | Your Definition of Success                       |
|---------------------------------------------------|---------------------------------------------------------------------|--------------------------------------------------|
| **Number of Users/Downloads**                     | Track downloads or registrations on the platform hosting the material | 1,000 users within the first three months        |
| **Course Completion Rate**                        | Percentage of users who complete the entire material                 | At least 70% of users complete the materials     |
| **User Engagement**                               | Average time spent, or interactions (like clicks) per session        | Users engage for an average of 30 minutes/session |
| **Diversity of User Base**                        | Track user demographics or geographic locations                      | Users from 25 different countries                 |
| **Feedback Score**                                | Aggregate score from user feedback forms                             | Average feedback score of 4.5/5                  |
| **Positive Testimonials**                         | Collect and categorize user testimonials                             | 15 in-depth positive testimonials                  |
| **Appreciation of the course** | Interviews with course participants | 70% of the participant interviews are largely positive | 
| **Collaborative Contributions**                   | Count of edits, additions, or collaborative actions on the material  | 50 community-contributed updates or edits         |
| **Integration in Learning Settings**              | Track the number of institutions or groups formally adopting the material | Adopted by 3 educational institutions            |
| **Quality of Learning Experience**   | Conduct focus group discussions or in-depth interviews               | Users report a richer understanding of the topic  |
| **Innovative Use Cases**             | Document and analyze instances where materials are used in unexpected ways | 5 documented innovative applications of the material |

:::
::::

<!-- This table blends quantitative metrics, which can be easily counted or measured, with qualitative insights, which give a richer, deeper understanding of the impact and value of the open educational materials. -->








### Planning for Openness: Practicalities

After laying a solid foundation through scoping, it's time to move into the practicalities of initiating an open education project. Every educational venture, open or otherwise, comes with its unique set of challenges. Open education, however, introduces its own nuances. From understanding the resources you need to committing the right amount of time, from developing a seamless content creation workflow to addressing copyright concerns, there's a lot to consider. This section aims to provide a guide on how to approach these facets, ensuring your open educational materials not only reach their intended audience but also are able to be updated and can stay relevant. 

The heart of an open education initiative is not just the content, but also the entire ecosystem around it. This ecosystem includes the tools you use, the community you engage, the licenses under which you operate, and the feedback loops you establish. Each of these elements requires careful thought and planning. In this section, we'll delve deep into each of these aspects, offering both advice and actionable steps. Whether it's ensuring every learner can access your materials regardless of their abilities, or fostering a vibrant community that actively uses and contributes to your resources, our goal is to prepare you for every eventuality. So, let's embark on this detailed exploration of the practicalities of open education.

**Resource and Time Commitment** <br>
Preparation is extremely important. Creating new materials is a timely process, and it's important to be realistic about the time and resources you have available. Although in @sec-benefits we mention that OERs can reduce cost for students, creating the materials can be costly. We need to understand the resources we have available and how we can use them effectively. 

Every initiative, regardless of its scale, requires some form of financial investment. It could be for the design and hosting of a platform, compensation for contributors, investment in technology, or promotion of the materials. Start by estimating a budget for each phase of your project. Consider all potential costs and try to anticipate unexpected expenses. Always allocate a contingency fund, as unexpected costs can and will arise. Be clear about the time you and your team can dedicate to the project as a result of the budget. This includes content creation, reviewing, updating, community engagement, and addressing feedback. Allocate sufficient time for each phase, keeping in mind that some phases may overlap or take longer than anticipated.

::: {.callout-note}
# Example of a budget
Do we have one lying around that we can share? Or create a ficitve one. 
:::



**Platform and Content** <br>

Deciding on platform and content cannot fully be seen as independent from each other. If you decide to use certain content types, e.g. videos, PowerPoint, PDFs, you will need to consider the platform that can host these content types. If you decide to use a certain platform, you will need to consider the content types that can be hosted on the platform you choose. Do these match? Can we make it work? If not, you will need to reconsider either the platform or the content types. @sec-resources helps you with some practical options to choose your resources and @sec-example_courses shows examples of how others have done it. There will be many more options out there that we do not describe, so feel free to explore and find what works for you. The planning stage is however the stage to make these decisions. We will guide you through the process of making these decisions.

What are some of the considerations you need to make when choosing a platform and content types?

Content Creation Workflow
- quality control, do you have collaborators? Do you collaborate online on the platform or do you create the content offline and then upload it to the platform?
Detail the steps from drafting, reviewing, editing, to publishing. Discuss tools that can help streamline this process.

Distribution & Outreach: Once materials are created, how will they be distributed? Will they be hosted on a specific platform, sent out via email, shared on social media? Ensuring Accessibility: Tools, tips, and best practices to make sure all materials are accessible to a diverse audience. Training & Upskilling needed? Especially if the initiative introduces new tools/platforms, consider how you will ensure educators and students are comfortable using them.
 
Engagement. Feedback & Iteration: Processes to collect feedback and how it will be used to improve subsequent versions of the educational materials. Do you want to embrace the Holistic approach to open education as described in @sec-holistic_approach.  How to build and foster an active community around your resources. Consider discussing forums, feedback mechanisms, and other community-building tools.




**Licensing** <br>
Picking a license is not something most people will enjoy doing, but it is important to do so. It has consequences for the way you can use the material in future, and the way others can use it. It is also important to be consistent in the way you license your material. If you use different licenses for different parts of your material, it will be difficult for others to use it. Licencing is slightly complicated and we devote an entire section to it (@sec-licensing). So why do we name it here if there is another section giving you more information? Because it is one of the most important practical steps if you plan for open educational materials. What do you want others to be allowed to do with your materials? Do you need credits if others use it? Can they change it? Can they use it commercially? These are all questions that you need to answer before you can choose a license. Again, @sec-licensing will provide more guidance on this issue. But we list it in the tasks for planning so that each time you go through the cycle of starting to plan for open educational materials and you use this book, you will be reminded in the planning stage. 




ideas:


- Licensing & Copyright: 
- 

- 
- 




## Making it Open Retrospectively

1. Evaluating Existing Resources
2. Transforming and Adapting Content
3. Overcoming Challenges

```{mermaid}
%%| fig-cap: Note this figure is not yet ready and just here as an idea to put a sequence of actions as an overview.
%%| label: fig-making_it_open
timeline
  title Making it Open
  section Evaluating Existing Resources
    Scoping : What are current rules?
    Practicalities : Do you have source materials? 
                   : ...
  section Transforming and Adapting Content
    Considerations : accessibility
                   : updating and maintanance
    
```

See @fig-making_it_open for a quick overview of the steps described in this section.

## Licensing: The Legalities of Open Education {#sec-licensing}

### Intellectual Property, Copyright, and Public Domain
**Intellectual Property (IP)** refers to creations of the mind, such as inventions, literary and artistic works, designs, symbols, names, and images used in commerce. **Copyright** is a law that gives the owner of original work exclusive rights to its use and distribution, usually for a limited time, with the intention of enabling the creator to receive compensation for their investment in creativity. **Public Domain** refers to works whose exclusive intellectual property rights have expired, been forfeited, or are inapplicable.

In the educational context, IP rights play a critical role in determining how educational content can be used, shared, and distributed. Copyrighted materials, for example, are typically restricted in distribution and use, requiring permissions or licenses to share or adapt. Public domain materials, on the other hand, are freely available for use by anyone for any purpose.

Educators and institutions need to navigate these legal frameworks to utilize educational content effectively while adhering to legal and ethical standards. Understanding these terms and their implications is essential to avoid copyright infringement and promote the ethical use of resources. It is paramount

::: {.callout-note}
# Considerations for retroactively opening existing education
Making existing educational content openly accessible retroactively can involve complex legal and ethical considerations. Below are key aspects that should be addressed:

1. **Copyright Ownership:**
   - **Evaluation:** Assess who owns the copyright to the educational materials. They could be owned by the
   educator, the institution, or third-party contributors.
   - **Permissions:** If the copyright is not owned by the institution or individual aiming to make the
   materials open, permissions must be obtained from the copyright holder to change the licensing or
   distribution terms.
2. **Third-party Content:**
   - **Identification:** Identify any third-party content embedded within the educational materials. This
   could include images, text, videos, or other media.
   - **Licensing:** Determine the licensing terms of the third-party content. Some may have restrictions on
   reuse or distribution that could complicate making the primary educational materials open.
3. **License Selection:**
   - **Compatibility:** Choose a license that is compatible with the intentions for use and distribution of
   the materials. Creative Commons licenses (see @sec-creativecommons) are often used for this purpose.
   - **Clarity:** Be clear on the permissions, restrictions, and requirements of the selected license. Make
   sure this information is clearly communicated to potential users of the materials.
4. **Ethical Considerations:**
   - **Privacy:** If the materials include contributions from students or other participants, consider
   privacy and consent issues. It may be necessary to anonymize or remove certain content.
   - **Quality:** Ensure that opening up the materials doesn’t compromise the quality or integrity of the
   educational content.
5. **Technical Aspects:**
   - **Accessibility:** Ensure that the materials are accessible, including considerations for individuals
   with disabilities. This could involve adding alternative text for images, ensuring website compatibility
   with screen readers, etc.
   - **Formats:** Consider the formats in which the materials will be made available. They should be in
   formats that are easy to access, use, and adapt.
6. **Community and Cultural Sensitivities:**
   - **Respect:** Be mindful of content that might be culturally sensitive or specific to a certain
   community. Opening content should be done respectfully and inclusively.

An existing course containing copyrighted readings, lectures notes authored by the teaching team, and - perhaps - student-contributed content would need a thorough evaluation. The copyrighted readings would require permission from the copyright holders or replacements with newly developed or open-access alternatives. The lecture notes could potentially be released under a Creative Commons license if the authors agree. Any student-contributed content would require considerations for privacy and consent before being made openly accessible.

Retroactively opening existing educational content is a commendable step towards open education, but it comes with its own set of complexities. Balancing legal requirements, ethical considerations, and the goal of openness requires a thorough, nuanced approach. Institutions and educators should engage in careful planning, consultation, and execution to navigate the intellectual property and copyright landscape effectively, ensuring that the opened materials are not only accessible but also legal and ethical in their availability and use.
:::

## Some terminology
**Copyright** is a law that gives the creator of original work exclusive rights to its use and distribution, typically for a limited time, with the intention of enabling the creator to receive compensation for their creative investment. Copyright applies to a wide range of creative, intellectual, or artistic forms. These include poems, theses, plays, other literary works, movies, dances, musical compositions, audio recordings, paintings, drawings, sculptures, photographs, software, radio and television broadcasts, and industrial designs.

**Copyleft** is a general method for making a program (or other work) free, and requiring all modified and extended versions of the program to be free as well. The simplest way to make a program free is to put it in the public domain, uncopyrighted. But this allows proprietary modifications: anyone can take the code, modify it and sell it as a proprietary product. To prevent this, the copyleft uses copyright law to ensure that every person who receives a copy or derived version of a work can use, modify, and also distribute both the work and derived versions of the work. Copyleft licenses (for software) require that information necessary for reproducing and modifying the work must be made available to recipients of the executable. The source code files will usually contain a copy of the license terms and acknowledge the authors.

**License Compatibility** is a legal framework that allows for pieces of software with different software licenses to be distributed together. The need for such a framework arises because the different licenses can contain contradictory requirements, rendering it impossible to legally combine source code from separately-licensed software in order to create and publish a new program. License compatibility can be particularly complex with copyleft licenses, which require derivative works to be licensed under a copyleft license. The concept of license compatibility applies to combining or merging software code that is provided under two different software licenses, and can also be a significant issue when trying to combine code placed under a copyleft license with proprietary software. 

An example of this complexity could be seen when trying to merge code from projects that are under different versions of the GNU General Public License (GPL). They might have requirements that are technically legal to fulfill yet practically difficult for the merged project to adhere to simultaneously. 

### Examples and Practical Implications:

- **Copyright**: A book author automatically having exclusive rights to their work, meaning others can't reproduce, distribute, or create derivative works without permission.
- **Copyleft**: A software developer releasing a program under the GNU GPL, meaning anyone can use, modify, and distribute it, but any derivative work must be released under the same license.
- **License Compatibility**: An open-source project trying to integrate code under both the Apache License and the MIT License, needing to ensure that the terms of both licenses can be satisfied simultaneously.

Each of these terms plays a significant role in how intellectual property, especially software and written works, is managed, distributed, and modified in the real world. This also applies to OER. Understanding them is vital for anyone involved in creating, using, or distributing such works, to ensure legal and ethical compliance as well as widespread usability and accessibility.

## Common licenses and organizations 

### Creative Commons: CC-BY & CC-BY-SA {#sec-creativecommons}
**Creative Commons (CC)** is a non-profit organization that provides free licenses and tools that copyright owners can use to allow others to share, reuse, and remix their material, legally ([Creative Commons](https://creativecommons.org/)). CC licenses are a simple way to give permissions for use of copyrighted works, fostering an accessible digital culture.

Creative Commons licenses are not alternatives to traditional copyright, but rather, they work alongside it. Traditional copyright law inherently restricts the right to copy, distribute, display, and perform protected works, as well as the right to make derivative works. In contrast, Creative Commons licenses help copyright owners grant some of their rights to the public while retaining others through a variety of licensing and contract schemes. Creative Commons licenses facilitate a culture of sharing and adaptation, crucial in open education, where resources are meant to be widely distributed and adapted. 

There are several important CC licenses that are commonly used in open education:

- **CC-BY (Attribution)**: This license allows others to copy, distribute, display, and perform the work and derivative works based upon it, but only if they give the author or licensor the credits in the manner specified by these. This is the most flexible CC license in terms of what others can do with the works.

- **CC-BY-SA (Attribution-ShareAlike)**: This license lets others remix, tweak, and build upon the work even for commercial purposes, as long as they credit the author and license their new creations under the identical terms. This license is often compared to open source software licenses.

- **CC-BY-NC-SA (Attribution-NonCommercial-ShareAlike)**: This license allows others to remix, adapt, and build upon the work non-commercially, as long as they credit the author and license their new creations under the identical terms. It’s suitable for creators who want to encourage the sharing and adaptation of their works while restricting their use to non-commercial purposes.

Each type of Creative Commons license provides a different level of freedom, catering to a variety of needs for both content creators and users, promoting a collaborative and sharing culture while respecting the rights of the original creators.

#### Applying Creative Commons licenses in open education

CC licenses are integral in open education, enabling the free use and adaptation of educational materials. For instance, the **MIT OpenCourseWare** ([MIT OCW](https://ocw.mit.edu/index.htm)) project uses a CC-BY-NC-SA license to allow users to freely use, adapt, and share course materials, provided they give appropriate credit, not use them for commercial purposes, and distribute their adaptations under the same license.

Similarly, **OER Commons** ([OER Commons](https://www.oercommons.org/)) provides a plethora of teaching and learning materials under various CC licenses, granting educators the flexibility to use, adapt, and share resources in compliance with the specified terms.

### Other relevant organizations and licenses
Aside from Creative Commons licenses, there are other licensing options and frameworks that are relevant to open education and OER. We list three of the most prominent licensing families below.

1. The [GNU Project](https://www.gnu.org/licenses/licenses.html) is a free software, mass collaboration project with the goal to give computer users freedom and control in their use of their computers and computing devices by collaboratively developing and publishing software that gives everyone the rights to freely run the software, copy and distribute it, study it, and modify it. The GNU Project has developed a number of licenses that are commonly used in open science:
   
   - **GNU General Public License (GPL)**: This license, commonly used for software, allows users to freely use, modify, and distribute software and software-based works. It requires that any derivative work also be distributed under the same license.
   - **GNU Free Documentation License (GFDL)**: Created for manuals, textbooks, and other functional and instructional materials, allowing them to be copied, distributed, and modified provided derivative works are under the same license.

2. The [Apache Software Foundation](https://www.apache.org) is an American nonprofit corporation to support a number of open-source software projects. The foundation is known for its support for the Apache HTTP Server, the world's most used web server software. The foundation developed the Apache license:
   
   - **Apache License 2.0** A permissive free software license written by the Apache Software Foundation, allowing users to use the software for any purpose, to distribute it, to modify it, and to distribute modified versions of the software under the terms of the license.
   - **Educational Community License 2.0:**: A modified Apache 2.0 license by the [open source initiative](https://opensource.org/license/ecl-2-0/) that change the scope of the patent grant to be specific to the needs of the education communities using this license. The Educational Community License is specifically crafted for the higher education community. It allows others to use, modify, and distribute educational materials similarly to CC and open source licenses.

3. The Massachusetts Institute of Technology has developed a permissive free software license in the late 1980s
   
   - **MIT License**: A permissive free software license originating at the Massachusetts Institute of Technology. It's a short, simple license allowing users to do anything they want with the material as long as they include the original copyright notice and disclaimers. As a permissive license, it puts only very limited restriction on reuse and has, therefore, high license compatibility.

Understanding the nuances of intellectual property, copyright, and public domain is fundamental to navigating the legal landscape of open education. Creative Commons licenses offer a balanced approach, granting educators and learners the freedom to use, adapt, and share educational materials while respecting the rights of original creators. This dynamic fosters an environment of collaboration, innovation, and accessibility in education, aligning with the ethos of an open, inclusive, and innovative learning culture.

Incorporate appropriate citations, and ensure that the provided links and resources are thoroughly reviewed and aligned with the specific focus of your chapter and book. Adjust the text as needed to fit the overall tone, style, and depth of your work. 

**Add link to license chooser tool**

**voorstel, audio discussie fragment opnemen over waarom helemaal open of toch net niet. discussie tussen gerko en jonathan? Jonathan vragen of hij dit wil doen. **

## Recap: Steps to Start an Open Education Initiative

- Identifying Your Goals and Audience
- Selecting Suitable Content and Format
- Navigating Licensing and Legal Aspects
- Planning for Accessibility and Inclusivity
- Collaborating with Others in the Community


